# check https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

blank_issues_enabled: false
contact_links:
  - name: enca documentation
    url: https://ossrevival.org/enca/
    about: Check the documentation, before asking questions.
